import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from './layout'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welkom bij bier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welkom bij <a href="https://nextjs.org">bier!</a>
        </h1>

        <p className={styles.description}>
          Vind hier verschillende soorten{' '}
          <code className={styles.code}>speciaal bier</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Blond &rarr;</h2>
            <p>Een frisse dorstlesser voor op het terras in de lente en zomer.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Tripel &rarr;</h2>
            <p>Een heerlijk zoet biertje met een wat zwaarder alcohol percentage.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Bock &rarr;</h2>
            <p>Of je nou lente of herfst bock hebt, wees ervan verzekerd dat het in een rond glas zit.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>IPA &rarr;</h2>
            <p>
              Indian Pale Ale komt ondanks de naam uit Engeland en staat bekend om de fruitige geur en bittere nasmaak.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home